name: Workflow with Email Identifier

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3000982@ds.study.iitm.ac.in
        run: echo "Hello, this step includes my email."
